version: '3'

services:

  frontend:
    image: "grocy/frontend:v3.3.2"
    build:
      args:
        GROCY_VERSION: v3.3.2
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-frontend
    depends_on:
      - backend
    networks:
      - internal
      - reverse_proxy_frontend
    tmpfs:
      - /tmp
    restart: unless-stopped
    #ports:
      #- 8082:8080
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grocy.rule= Host(`rpi1.polbel.casa`) && PathPrefix(`/grocy`)"
        - "traefik.http.services.grocy.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.grocy_path.replacepathregex.regex=/grocy(.*)"
        - "traefik.http.middlewares.grocy_path.replacepathregex.replacement=$$1"
        - "traefik.http.routers.grocy.middlewares=grocy_path@docker"
        - "traefik.docker.network=reverse_proxy_frontend"
        #- "traefik.http.routers.grocy.middlewares=grocy_strippath@docker"
        #- "traefik.http.middlewares.grocy_strippath.stripprefix.prefixes=/grocy"
      placement:
        constraints:
          - node.labels.type!=nas

  backend:
    image: "grocy/backend:v3.3.2"
    build:
      args:
        GROCY_VERSION: v3.3.2
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-backend
    networks:
      - internal
    tmpfs:
      - /tmp
      - /var/www/data/viewcache:mode=755,uid=82,gid=82,size=16m
    volumes:
      - app-db:/var/www/data
    env_file:
      - grocy.env
    restart: unless-stopped
    environment:
      - GROCY_BASE_URL=http://rpi1.polbel.casa/grocy
    deploy:
      placement:
        constraints:
          - node.labels.type!=nas
          
volumes:
  app-db:

networks:
  internal:
  reverse_proxy_frontend:
    external: true
