version: '3'

services:

  frontend:
    image: "grocy/frontend:v4.0.3"
    build:
      args:
        GROCY_VERSION: v4.0.3
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-frontend
    depends_on:
      - backend
    ports:
      - '127.0.0.1:8080:8080'
    tmpfs:
      - /tmp
    restart: unless-stopped

  backend:
    image: "grocy/backend:v4.0.3"
    build:
      args:
        GROCY_VERSION: v4.0.3
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-backend
    expose:
      - '9000'
    tmpfs:
      - /tmp
      - /var/www/data/viewcache:mode=755,uid=82,gid=82,size=16m
    volumes:
      - app-db:/var/www/data
    env_file:
      - grocy.env
    restart: unless-stopped

volumes:
  app-db:
